Try to fix error C2487 from MSVC, as it sound like export class member is not recognized by this compiler. Regression check must be done with GCC and CLang